<a href="https://colab.research.google.com/github/chodalahari/LLM/blob/main/tokenization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
text = "I love Python programming"
tokens = text.split()

print(tokens)


['I', 'love', 'Python', 'programming']


In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

text = "Hugging Face makes NLP easy"
tokens = tokenizer.tokenize(text)

print(tokens)


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

['hugging', 'face', 'makes', 'nl', '##p', 'easy']


In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Download required data (run once)
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

text = "Natural Language Processing is very interesting and useful"

# Tokenization
tokens = word_tokenize(text)

# Stopword removal
stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word.lower() not in stop_words]

print(filtered_tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


['Natural', 'Language', 'Processing', 'interesting', 'useful']


In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

text = "Subword tokenization is powerful"
tokens = tokenizer.tokenize(text)

print(tokens)


['sub', '##word', 'token', '##ization', 'is', 'powerful']


In [ ]:
from nltk.tokenize import word_tokenize

text = "NLP"
tokens = list(text)

print(tokens)


['N', 'L', 'P']


In [ ]:
import nltk
from nltk.tokenize import sent_tokenize

nltk.download('punkt')   # run once

text = "I love NLP. It is very useful."
sentences = sent_tokenize(text)

print(sentences)


['I love NLP.', 'It is very useful.']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
from nltk.tokenize import word_tokenize

text = "I love NLP."
words = word_tokenize(text)

print(words)


['I', 'love', 'NLP', '.']


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = np.array([["cat"], ["dog"], ["fish"]])

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(data)

print(encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

documents = ["I love NLP", "I love Machine Learning"]

vectorizer = CountVectorizer()
bow = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("BoW Matrix:\n", bow.toarray())


Vocabulary: ['learning' 'love' 'machine' 'nlp']
BoW Matrix:
 [[0 1 0 1]
 [1 1 1 0]]


In [ ]:
import gensim.downloader as api

# Load pretrained GloVe model
glove = api.load("glove-wiki-gigaword-50")

# User input
word = input("Enter a word: ").lower()

if word in glove:
    print("GloVe Embedding:")
    print(glove[word])
else:
    print("Word not found in GloVe vocabulary")

[==================================================] 100.0% 66.0/66.0MB downloaded
Enter a word: science
GloVe Embedding:
[-6.0334e-01  1.0577e+00 -3.0452e-01  5.6728e-02  6.2269e-04 -1.5874e-01
 -3.9343e-01 -1.6816e+00  2.5751e-01  9.6477e-02  2.2256e-01  4.0022e-01
 -1.3319e-01  5.0095e-01 -3.1653e-01 -1.3437e-01  3.6205e-01  1.1403e+00
 -4.6058e-01  7.8453e-01  1.1051e+00  6.7427e-01  3.3348e-01 -1.9985e-01
  8.8040e-01 -1.5153e+00 -1.0876e+00 -9.7803e-01 -1.0249e+00 -8.1350e-02
  2.6487e+00 -4.7125e-01 -4.5275e-01 -2.0287e+00 -4.0910e-01  2.6637e-01
 -6.6804e-01  1.1231e+00  8.9049e-01  2.0298e-01 -2.4961e-02 -4.6865e-01
  2.5623e-01  3.7514e-01 -1.2434e-01  7.2878e-01  9.0596e-01  8.3551e-01
  2.2837e-04  4.4761e-01]


In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 76.0 MB/s eta 0:00:00


In [ ]:
from transformers import BertTokenizer, BertModel
import torch

# Load pretrained BERT
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")

text = "I love Natural Language Processing"

# Tokenize
inputs = tokenizer(text, return_tensors="pt")

# Get embeddings
with torch.no_grad():
    outputs = model(**inputs)

# Last hidden state (token embeddings)
token_embeddings = outputs.last_hidden_state

print(token_embeddings.shape)


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

torch.Size([1, 7, 768])


In [ ]:
from gensim.models import Word2Vec

sentences = [
    ["i", "love", "nlp"],
    ["nlp", "is", "powerful"],
    ["i", "enjoy", "machine", "learning"]
]

model = Word2Vec(
    sentences,
    vector_size=100,
    window=5,
    min_count=1,
    sg=1   # 1 = Skip-Gram, 0 = CBOW
)
vector = model.wv["nlp"]
print(vector.shape)


(100,)
